
package com.airhacks.jwtenizr.control;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;

/**
 *
 * @author airhacks.com
 */
public interface MicroProfileConfiguration {

    public static void generate(String publicKey) throws IOException {
        Properties properties = new Properties();
        properties.put("mp.jwt.verify.publickey", publicKey);
        properties.store(new FileWriter("microprofile-config.properties"), "generated by jwtenizer");
    }

}
