
package com.airhacks.jwtenizr.control;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

/**
 *
 * @author airhacks.com
 */
public interface MicroProfileConfiguration {

    public static void generate(String publicKey) throws IOException {
        String location = Configuration.mpConfigurationLocation();
        Properties properties = new Properties();
        properties.put("mp.jwt.verify.publickey", publicKey);
        Path path = Paths.get(location, "microprofile-config.properties");
        properties.store(new FileWriter(path.toFile()), "generated by jwtenizer");
    }

}
